# Generated by Django 4.1.2 on 2022-10-19 03:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='user',
            field=models.CharField(default=-2022, max_length=225),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='storage',
            name='access_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 19, 8, 37, 32, 299022)),
        ),
    ]
