# Generated by Django 4.1.2 on 2022-10-19 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_storage_user_alter_storage_access_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='access_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 19, 21, 25, 19, 22302)),
        ),
    ]
