# Generated by Django 4.1.2 on 2022-10-21 08:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_storage_access_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='access_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 21, 13, 55, 49, 658480)),
        ),
    ]
