# Generated by Django 4.1.2 on 2022-10-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_users_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profilePic',
            field=models.ImageField(upload_to='profilePics'),
        ),
    ]
